version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "customersResolverStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rm337rch45b7"
s3_prefix = "customersResolverStack"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
